plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

application {
    mainClass = 'chin.Chin'
}

run {
    standardInput = System.in
}

jar {
    archiveBaseName = 'chin'
    archiveVersion = ''
    manifest {
        attributes 'Main-Class': 'chin.Chin'
    }
}
